### ISSUE TITLE
Move common script into base classes

### ISSUE THREAD

**Issue by yodurr** [Microsoft/windows-dev-box-setup-scripts#2]
Would be cool to have a dev.ps1 that provides common dev script commands, then the scenario specific scripts can just have the particular tool differences.

One of the challenges is including other ps1 scripts is hard when your starting point is clicking a web link that kicks off boxstarter.  The ability to make install 1-click and not require cloning this repo seems more important than the ability to create base class scripts.

**Comment by crutkas** [comment]
Tried doing an PS invoke to another PS file on my github that was refactored out but got the error below:
`invoke-expression -Command https://raw.githubusercontent.com/crutkas/windows-dev-box-setup-scripts/master/helper_WindowsExplorerSettings.ps1
`

> ERROR: The term 'https://raw.githubusercontent.com/crutkas/windows-dev-box-setup-scripts/master/helper_WindowsExplorerSettings.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
> The install of tmp2d69.tmp was NOT successful.
> Error while running 'C:\ProgramData\chocolatey\lib\tmp2D69.tmp\tools\ChocolateyInstall.ps1'.
>  See log for details.

**Comment by crutkas** [comment]
I have a branch that does this now

What I think as part of this would be see if we can’t pass in Args too so we can have one master and then the subpages just call the master with overrides via args.

**Comment by crutkas** [comment]
https://github.com/Microsoft/windows-dev-box-setup-scripts/tree/BreakUpScripts?files=1

**Comment by yodurr** [comment]
Woot!  This will be a big help.  Can't wait to make this the new normal.

**Comment by crutkas** [comment]
think this can be tested now.  once the devapp.ps1 you're happy with, we can either 

- work on the calling URL so we don't have to alter / include URL and branch
- work on proper enums vs calling scripts directly
- port others over (then do top 2)

**Comment by yodurr** [comment]
PR #59 created

**Comment by yodurr** [comment]
done.
