### ISSUE TITLE
Add common dev tools automatically upon install of WSL distro

### ISSUE THREAD

**Issue by DarthSpock** [Microsoft/windows-dev-box-setup-scripts#33]
Instead of having to manually download packages commonly used by developers every time you install/reinstall a distro for WSL (and thus being forced to create your own scripts), we should add this to the dev-box-setup experience. For instance for the web development we could use `wsl.exe apt install build-essentials npm` `wsl.exe npm install node`, etc. Noting of course `wsl.exe` will launch the default distro, which is the first one installed. Using `wslconfig.exe` should probably be included as a commented out portion to change the default distro if more than one is installed.

**Comment by yodurr** [comment]
I agree - we're discussing how best to do this as the user creation step in the distro is currently in the way.  Changing behavior to creating a default user with blank password may be the best path forward.

**Comment by DarthSpock** [comment]
> Changing behavior to creating a default user with blank password may be the best path forward.

https://github.com/Microsoft/WSL-distrolauncher has what you need in that regard, but how that would work for distros installed from the Store is a different story since that's controlled by the distro maintainer. Perhaps we could automate the user creation process with a password of something like password, make the changes, and removing the account, thus causing a prompt for username to appear.

**Comment by yodurr** [comment]
We're talking to the distro maintainers about enabling installation with a default user w/blank password.  That seems like the best outcome for scripted install.

**Comment by DarthSpock** [comment]
Would such a script then be portable enough to work for non-partner distros? For example, the script may work great for Ubuntu but would users be able to follow the same script for Arch Linux with the only very noticeable change being the name of the installation from saying "Ubuntu" to "Arch Linux" (via UI prompt)?

**Comment by yodurr** [comment]
I believe so because we'd show how to do it in the distro launcher project.  it would be up to the distro to support it.

**Comment by DarthSpock** [comment]
That should be enough in theory. Just trying co-relate the other issue I made for automating installation of side-loaded distros. The user creation script sounds directly tied to that effort. The script will eventually need to be tied in for automation but with the current install mechnism, documentating it would be sufficient.

**Comment by yodurr** [comment]
we'll make sure to document it. 
@tara-raj FYI

**Comment by yodurr** [comment]
Check out #68 
It's coming :)

**Comment by yodurr** [comment]
Done!
