### ISSUE TITLE
Please don't force reinstall

### ISSUE THREAD

**Issue by JanMulkens** [Microsoft/windows-dev-box-setup-scripts#36]
When trying to combine scripts (for example: Machine Learning / Web), software gets forcefully reinstalled.
This seems like a waste of time and bandwith if the version is matching the one you currently have.

Is it possible to not do this or is there a specific reason why this is being done?

**Comment by gep13** [comment]
@JanMulkens can you confirm if you are seeing this problem when you try to run the script twice?  Or are you seeing this when using the script for the first time?

**Comment by mwrock** [comment]
This is actually a known choco/boxstarter bug. Boxstarter reverted the choco library that intoduced this bug but that fix was not deployed to the latest click once app. We are planning a new click once deployment next week that should remove this problem.
