### ISSUE TITLE
Include samples with the installed software

### ISSUE THREAD

**Issue by JanMulkens** [Microsoft/windows-dev-box-setup-scripts#37]
It would be lovely to have samples included (or have them in a separate script to install) for each of the different scripts.
This would open these scripts to not only experienced developers wanting to save time, but potentially also to unexperienced people wanting to try something out and needing that little bit of extra guidance.

**Comment by gep13** [comment]
@JanMulkens sorry, but I am not sure if I follow what you are suggesting here.  Can you elaborate?

**Comment by yodurr** [comment]
I think he's asking for sample projects to go along with the tools.  This would be cool for scripts designed to give you an intro into an area.
  
I could see having a folder for each area and in that alongside the base setup scripts, include one that fetches samples.  Or we could have them in the scripts commented out.

**Comment by crutkas** [comment]
doing this as part of the desktop script.  I'm installing git samples off of https://github.com/Microsoft/Windows-universal-samples to the desktop

**Comment by JanMulkens** [comment]
@gep13 , is this clear enough or do you still need me to elaborate?

**Comment by gep13** [comment]
@JanMulkens assuming that @yodurr and @crutkas have your intention correct, then I think we are good 👍

**Comment by yodurr** [comment]
this is now in master for app dev.  We're discussing if there are other ways to support this in a general way - perhaps have a switch for "include samples", etc.  Welcome feedback on this.
