### ISSUE TITLE
You don't cinst pip

### ISSUE THREAD

**Issue by majkinetor** [Microsoft/windows-dev-box-setup-scripts#39]
Because pip comes with python.

**Comment by gep13** [comment]
@majkinetor do you know if this is true of all versions of Python, or only the latest version?

**Comment by gep13** [comment]
@majkinetor I have just done a quick test, and it looks like when doing `choco install python2` the pip.exe is available in the scripts folder.  It isn't directly accessible from the command line.  I am not a Python developer, so I don't know if this is expected or not.  Should the python package create a shim for the pip.exe?

I can take an action to speak with @ferventcoder about deprecating the pip package.

**Comment by gep13** [comment]
I have removed the `choco install pip` commands.

**Comment by majkinetor** [comment]
> Should the python package create a shim for the pip.exe?

Give us a ticket at coreteam-repo for this as everybody expectes pip to just work.

**Comment by gep13** [comment]
Sounds like a plan! 👍

**Comment by gep13** [comment]
Issue created here: https://github.com/chocolatey/chocolatey-coreteampackages/issues/1032
