### ISSUE TITLE
Drivers management part of the automation process

### ISSUE THREAD

**Issue by nunix** [Microsoft/windows-dev-box-setup-scripts#41]
First of all, thanks a lot for this great automation tool. I used the "Web" default package and just had to relax and wait for the install.

However, as I have a new computer from work to act as a "Innovation sandbox" (read: out of domain and no corporate support), it triggered a doubt/need for enhancement:
Could this tool be used to manage also the drivers? I know there's business tools and/or prep tools that can be used.
But the learning curve compared to this tool/automation are simply too big.

The idea, would be to handle the "double" install we have with the drivers (1 package > uncompressed installation files > launches the actual setup) and following the model (which we can have as an input), would gather the drivers from a repo (usb key, shared drive, other?)

Hopefully this makes sense to someone else more than me.

Keep the excellent work!

**Comment by nunix** [comment]
@gep13 thanks a lot for the feedback and in "my current" case, it's really only to configure the drivers of a laptop.

So it would be something indeed based on your `geforce` example.

I will deep dive into the script in the coming days/weeks and if I find a way I will share it for sure.

Thanks again for the feedback.

PS: this issue can be closed for now then 😁

**Comment by gep13** [comment]
@nunix perfect.  Let us know if you have any follow up questions.
