### ISSUE TITLE
first time trying to launch, you need to double launch

### ISSUE THREAD

**Issue by crutkas** [Microsoft/windows-dev-box-setup-scripts#43]
this may be a boxstarter issue but when launching the script and it isn't installed already, you have to actually relaunch after boxstarter has installed versus having it accept the data passed in and continue to execute

**Comment by yodurr** [comment]
Confirmed am seeing this as well now on Windows 1803.  This is new behavior.  

The good thing is it seems like it actually works now and whatever was causing https://github.com/chocolatey/boxstarter/issues/301
might be resolved.

**Comment by crutkas** [comment]
tested on new VM and has been resolved on boxstarter end

**Comment by gep13** [comment]
>@crutkas said...
tested on new VM and has been resolved on boxstarter end

I am fairly sure that we haven't changed anything, or rather, I haven't done anything, and I was the one who pushed out the latest release of Boxstarter.  I don't think @mwrock or @ferventcoder have made any changes either.

I am happy to hear that this is now working, but I would like to know what, if anything, has changed.

@yodurr is this also now working for you?

Is it just a case of the Chocolatey Code Signing Certificate having gathered enough positive reputation to not trip up any Defender, or other, products?
