### ISSUE TITLE
Hey the Ubuntu WSL link in the scripts is outdated. 

### ISSUE THREAD

**Issue by thedonquixotic** [Microsoft/windows-dev-box-setup-scripts#58]
Link is for 16.04 but not for 18.04 which from what I can tell is only available through third party links or the Windows Store. 

I haven't tried this yet but I believe this powershell script should work. 

```
Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
Get-AppxPackage -name "*Ubuntu*18*" | Add-AppxPackage
```

**Comment by yodurr** [comment]
not all the store distros work from command line install.  Makes sense to enable ubuntu 18 if it isn't already enabled.  @tara-raj

**Comment by thedonquixotic** [comment]
It's enabled but I was not able to find a way to install from CLI, had to do it manually in the store which was no big deal.

**Comment by thedonquixotic** [comment]
Excellent thanks. I'll close.
