### ISSUE TITLE
Auto creation of 1-click links in Readme

### ISSUE THREAD

**Issue by yodurr** [Microsoft/windows-dev-box-setup-scripts#6]
The Readme should contain links to every script that you can click to trigger install.
Doing this requires a job that updates the links every time the hash for them changes - the link will include the link to the raw script content.

Could we use appveyor to update the script links in the readme after every commit?

**Comment by amankkg** [comment]
I wonder how executable is being generated from PS scripts? Maybe it's worth adding a section in readme?

**Comment by yodurr** [comment]
I see - more details on how boxstarter works?  We can add this to the readme, does that address your questions?
https://boxstarter.org/Learn/WebLauncher

**Comment by amankkg** [comment]
Ah, yes, I see now

**Comment by gep13** [comment]
@amankkg would you like to create a PR to provide some additional information around this in the readme.md?

**Comment by yodurr** [comment]
We don't need to re-generate the links now that this repo is public.  Closing this issue.  I'll add a readme entry with the WebLauncher link.
