### ISSUE TITLE
Need to reboot after installing WSL

### ISSUE THREAD

**Issue by yodurr** [Microsoft/windows-dev-box-setup-scripts#60]
Noticed we're not rebooting during script run, so the user has to reboot manually before they can run WSL.

**Comment by yodurr** [comment]
and if we reboot we need to prompt for password at the start of the script run...

**Comment by yodurr** [comment]
@mwrock for the reboot to work we need to cache the password right but we're currently running with the NoRestart flag probably because we never prompt for the password.  How do we get a click-once based launch to also leverage restart and request the password?

**Comment by mwrock** [comment]
You just need to remove the `/nr` from the URL. Then the app should prompt and reboot if necessary.

**Comment by yodurr** [comment]
thanks.  what if the user has a blank password?  It looks like boxstarter doesn't like that answer in the password prompt.  Known issue?

**Comment by mwrock** [comment]
not a known issue afaik but likely an issue that needs to be raised.

**Comment by yodurr** [comment]
Ok, we'll get the URI fixed here and submit a separate issue on boxstarter for blank password.  Thanks.

**Comment by yodurr** [comment]
Addressed in commit #66
