### ISSUE TITLE
Update Ubuntu distro to the latest, now it is 1804

### ISSUE THREAD

**Issue by ddieppa** [Microsoft/windows-dev-box-setup-scripts#64]
Based on this article [Manually download WSL distro packages](https://docs.microsoft.com/en-us/windows/wsl/install-manual), I think will be fine just to change the version number in the **Ubuntu** section on the [VirtualizationTools.ps1](https://github.com/Microsoft/windows-dev-box-setup-scripts/blob/master/scripts/VirtualizationTools.ps1) script

**Comment by yodurr** [comment]
Agreed.  Hoping to get this in before the weekend.

**Comment by ddieppa** [comment]
It should be an easy change that I can help with, but I don't know how to test the entire thing and go throw the process or create a pull request, etc :(

**Comment by yodurr** [comment]
Yeah it's not complicated.  Thanks for the note - I will add contribution steps to the readme to outline how to contribute.

**Comment by yodurr** [comment]
Addressed in commit #66
