### ISSUE TITLE
Change to boxstarter.org infrastructure

### ISSUE THREAD

**Issue by gep13** [microsoft/windows-dev-box-setup-scripts#99]
I just wanted to give a heads up that we, @chocolatey, have just made some changes to the Boxstarter website, in terms of where it is hosted.

We have run some tests, and from what we can see, everything is working as it was previously, but if anyone here does notice any problems, please feel free to reach out so that we can address them.

@crutkas and @yodurr is there anyone else that we should ping about this change?

Including @pauby and @windos for visibility.

**Comment by crutkas** [comment]
Thanks for the heads up!
